POST http://localhost:9000/register
Content-Type: "application/json"

{
    "id": 1,
    "email": "aqil@mail.com",
    "password": "123456"
}

POST http://localhost:9000/register
Content-Type: "application/json"

{
    "id": 1,
    "email": "aqilmai",
    "password": "123456"
}

POST http://localhost:9000/login
Content-Type: application/json

{
    "email": "aqil@mail.com",
    "password": "123456"
}

